# Site settings
title: Code for America Style Guide
email: info@codeforamerica.org
description: |
  Code for America's style guide and front-end pattern library.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
permalink: /:categories/:title/

# Build settings
markdown: kramdown

collections:
  components:
    output: true
    permalink: /patterns/components/:path/
  atoms:
    output: true
    permalink: /patterns/atoms/:path/
  molecules:
    output: true
    permalink: /patterns/molecules/:path/
  organisms:
    output: true
    permalink: /patterns/organisms/:path/
  templates:
    output: true
    permalink: /patterns/templates/:path/
  developers:
    output: true
    permalink: /patterns/developers/:path/
